### PR TITLE
Use memmove for copy waterfal, remove smooth waterfal pan

### PR DESCRIPTION
**Pull request by gdyuldin**

### CODE REVIEW

**Comment by strijar** [comment]
I spent quite a lot of time on this smooth scrolling. It was specifically asked for it. I would suggest making it disable through settings.

**Comment by strijar** [comment]
Thank's!

**Comment by gdyuldin** [comment]
Found an issue with disabled waterfall smooth scroll. Will try to fix it.

**Comment by gdyuldin** [comment]
Added small delay for updating waterfall after freq change to fix issue

**Pull request closed without merging**
